import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#00174b',
        'secondary-fixed-dim': '#62df7d',
        'secondary-fixed': '#7ffc97',
        'tertiary': '#784b00',
        'on-error-container': '#93000a',
        'on-surface': '#141b2b',
        'inverse-primary': '#b4c5ff',
        'surface-variant': '#dce2f7',
        'surface-dim': '#d3daef',
        'on-secondary-fixed-variant': '#005320',
        'tertiary-container': '#996100',
        'secondary': '#006e2d',
        'primary-fixed': '#dbe1ff',
        'error-container': '#ffdad6',
        'surface-tint': '#0053db',
        'inverse-surface': '#293040',
        'background': '#f9f9ff',
        'outline': '#737686',
        'on-tertiary': '#ffffff',
        'primary': '#004ac6',
        'on-tertiary-container': '#ffeedd',
        'on-secondary': '#ffffff',
        'error': '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'on-surface-variant': '#434655',
        'secondary-container': '#7cf994',
        'surface': '#f9f9ff',
        'on-background': '#141b2b',
        'inverse-on-surface': '#edf0ff',
        'on-primary-fixed-variant': '#003ea8',
        'surface-container-low': '#f1f3ff',
        'surface-container-highest': '#dce2f7',
        'on-secondary-container': '#007230',
        'tertiary-fixed': '#ffddb8',
        'outline-variant': '#c3c6d7',
        'on-error': '#ffffff',
        'surface-bright': '#f9f9ff',
        'tertiary-fixed-dim': '#ffb95f',
        'on-primary-container': '#eeefff',
        'on-secondary-fixed': '#002109',
        'on-tertiary-fixed-variant': '#653e00',
        'surface-container': '#e9edff',
        'surface-container-high': '#e1e8fd',
        'primary-container': '#2563eb',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#b4c5ff',
        'on-tertiary-fixed': '#2a1700',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'gutter': '12px',
        'stack-md': '16px',
        'stack-lg': '24px',
        'stack-sm': '8px',
        'safe-area-bottom': '34px',
        'container-margin': '16px',
      },
      fontFamily: {
        'small': ['Inter'],
        'headline-md': ['Inter'],
        'body': ['Inter'],
        'headline-lg': ['Inter'],
        'plate-number': ['JetBrains Mono'],
      },
      fontSize: {
        'small': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '24px', fontWeight: '700' }],
        'body': ['15px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['22px', { lineHeight: '28px', fontWeight: '700' }],
        'plate-number': ['24px', { lineHeight: '32px', letterSpacing: '4px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}

export default config
